name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          cd newton && npm install   # (లేదా మీ application deployment/build command)

      - name: Restart Application
        run: |
          /usr/bin/pm2 restart all || /usr/bin/pm2 start app.js  # (లేదా మీ server start command)